# Generated by Django 5.0 on 2023-12-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_email_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='minutes_trained',
            field=models.IntegerField(default=0),
        ),
    ]
