# Generated by Django 5.0 on 2023-12-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='grappling_type',
            field=models.CharField(default='Gi'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='rob', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='rob', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
