# Generated by Django 5.0 on 2023-12-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_session_grappling_type_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
    ]
